# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-05-25 19:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_caption', models.CharField(max_length=200)),
                ('image_description', models.TextField(blank=True, null=True)),
                ('target_url', models.URLField(blank=True, null=True)),
                ('image_url', models.URLField()),
                ('display_description', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentationLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20, unique=True)),
                ('url', models.URLField(max_length=100)),
                ('displayed', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body_markdown', models.TextField()),
                ('body_html', models.TextField(editable=False)),
                ('description', models.CharField(max_length=140)),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('doi', models.CharField(blank=True, max_length=100, null=True)),
                ('entry_type', models.CharField(blank=True, max_length=100, null=True)),
                ('published_in', models.CharField(blank=True, max_length=200, null=True)),
                ('publisher', models.CharField(blank=True, max_length=200, null=True)),
                ('year_of_publication', models.CharField(blank=True, max_length=4, null=True)),
                ('month_of_publication', models.CharField(blank=True, max_length=10, null=True)),
                ('bibtex', models.TextField(blank=True, null=True)),
                ('is_highlighted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body_markdown', models.TextField()),
                ('body_html', models.TextField(editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('website_position_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('section_type', models.CharField(choices=[('fixed', 'Fixed Section'), ('page', 'Page')], default='page', max_length=100)),
                ('show_in_nav', models.BooleanField(default=False)),
            ],
            options={
                'permissions': (('view_section', 'Can see available sections'), ('edit_section', 'Can edit available sections')),
            },
        ),
    ]
