# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 18:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_newspost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('doi', models.CharField(blank=True, max_length=100, null=True)),
                ('journal', models.CharField(blank=True, max_length=200, null=True)),
                ('publisher', models.CharField(blank=True, max_length=200, null=True)),
                ('year_of_publication', models.CharField(blank=True, max_length=4, null=True)),
                ('month_of_publication', models.CharField(blank=True, max_length=4, null=True)),
                ('bibtex', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='newspost',
            name='post_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='websitesection',
            name='website_position_id',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
