# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-03-01 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_carouselimage_is_visible'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_caption', models.CharField(max_length=200)),
                ('image_description', models.TextField(blank=True, null=True)),
                ('target_url', models.URLField(blank=True, null=True)),
                ('image_url', models.URLField()),
                ('display_description', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('is_visible', models.BooleanField(default=True)),
            ],
        ),
    ]
