# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20160602_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='month_of_publication',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
