# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20160604_0343'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='is_highlighted',
            field=models.BooleanField(default=False),
        ),
    ]
