# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_carouselimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoneycombPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_caption', models.CharField(max_length=200)),
                ('image_url', models.URLField()),
                ('target_url', models.URLField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='websitesection',
            name='website_page',
            field=models.CharField(choices=[('home', 'Home'), ('installation', 'Installation'), ('overview', 'Overview')], max_length=100),
        ),
    ]
