# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-04 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_documentationlink_displayed'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselimage',
            name='image_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carouselimage',
            name='target_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
