# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-04 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20160704_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselimage',
            name='display_description',
            field=models.BooleanField(default=True),
        ),
    ]
