# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-16 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_carouselimage_display_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='description',
            field=models.CharField(default='sample description', max_length=140),
            preserve_default=False,
        ),
    ]
